### ISSUE TITLE
Create a default main boot entry

### ISSUE THREAD

**Issue by j-james** [CTCaer/hekate#541]
When setting up a new installation of Hekate, at least one main boot entry needs to be specified in `hekate_ipl.ini`.

It'd be nice if Hekate could detect and append a boot entry to a fresh install.

**Comment by urherenow** [comment]
It's left out on purpose (so you don't have to fix your settings with every upgrade).

**Comment by j-james** [comment]
Right, but so is the whole file. If you copy over a clean download of Hekate (with no configuration), a new `hekate_ipl.ini` file gets created with the following: 

```toml
[config]
autoboot=0
autoboot_list=0
bootwait=3
backlight=100
autohosoff=0
autonogc=1
updater2p=1
```

My suggestion would be to append to that file when it's first created with

```
[Atmosphere]
fss0=atmosphere/fusee-secondary.bin
```

or similar, depending on what the Switch is running.
