### ISSUE TITLE
emuMMC crashes with error 2162-0002 (boots fine with fusee.bin)

### ISSUE THREAD

**Issue by supaplexer** [CTCaer/hekate#959]
```
Model: Erista v1 unpatched (RCM)
OFW: 17.0.1
CFW: 17.0.1
AMS: 1.6.2
Hekate: 6.0.7 / 6.1.0 / 6.1.1
```

Since upgrading to Atmosphère 1.6.2 and Hekate 6.0.7, I'm unable to boot into my emuMMC. Atmosphère crashes with error 0x4a2 on either program 0100000000001000 (qlaunch) or 010000000000100C (overlayDisp) right after the boot logo.

```
Error Code: 2162-0002 (0x4a2)
Program: 0100000000001000
Firmware: 17.0.1 (Atmosphère 1.6.2-master-f7bf379cf)
```

The same error also happens with Hekate 6.1.0 and 6.1.1.

Crash logs:
https://gist.github.com/supaplexer/2785090ca749bea6b3f48c0d3e6d4ce0

I have never had any themes installed and I do not have any folder named after those programs under atmosphere/contents.
I have also completely wiped the atmosphere/contents folder but it still crashes when launched via Hekate.

The SD card is ExFAT + FAT32 and has 0 errors (checked both on Hekate and PC)
I CAN boot into stock OFW with no issues.

I CAN only boot my emuMMC via fusee.bin.

The reason why I'm filing this issue here and not on Atmosphère is indeed because injecting fusee.bin boots up my emuMMC just fine into ams 1.6.2 and everything works (even tesla overlays).

The hekate_ipl.ini in question is this:

```toml
[config]
autoboot=0
autoboot_list=0
bootwait=3
verification=1
backlight=100
autohosoff=0
autonogc=1
updater2p=1

[Atmosphere (emuMMC)]
fss0=atmosphere/package3
kip1patch=nosigchk
emummcforce=1
cal0blank=1
atmosphere=1
logopath=bootloader/res/bootlogo-emunand-f.bmp
icon=bootloader/res/icon_payload.bmp
```

These configuration worked just fine on hekate < 6.0.7 and ams < 1.6.2.

I could also mention I'm on a DeepSea-based cfw and exosphere + cal0blank=1 to block Nintendo servers.

This is my exosphere config:
```toml
[exosphere]
debugmode=1
debugmode_user=0
disable_user_exception_handlers=0
enable_user_pmu_access=0
blank_prodinfo_sysmmc=0
blank_prodinfo_emummc=1
allow_writing_to_cal_sysmmc=0
log_port=0
log_baud_rate=115200
log_inverted=0
```

Other config files:

atmosphere/config/override_config.ini
```toml
[hbl_config]
override_key_0=R
program_id_0=010000000000100D
```
atmosphere/config/system_settings.ini
```toml
[atmosphere]
dmnt_cheats_enabled_by_default = u8!0x0
```
